server:
  port: 10006
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/app-crawler?characterEncoding=UTF8
    username: guest
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
download:
  path: /Users/liufei/IdeaProjects/app-crawler/qq/